<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "attribute_type".
 *
 * @property integer $id
 * @property string $name
 * @property string $data_type
 * @property integer $list_of_values_id
 * @property string $description
 * @property string $created_at
 * @property string $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 *
 * @property \common\models\Attribute[] $attributes
 * @property \common\models\ListOfValues $listOfValues
 */
abstract class AttributeType extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'attribute_type';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'data_type'], 'required'],
            [['list_of_values_id', 'created_by', 'updated_by'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['name'], 'string', 'max' => 40],
            [['data_type'], 'string', 'max' => 255],
            [['description'], 'string', 'max' => 200],
            [['name'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('gip', 'ID'),
            'name' => Yii::t('gip', 'Name'),
            'data_type' => Yii::t('gip', 'Data Type'),
            'list_of_values_id' => Yii::t('gip', 'List Of Values ID'),
            'description' => Yii::t('gip', 'Description'),
            'created_at' => Yii::t('gip', 'Created At'),
            'updated_at' => Yii::t('gip', 'Updated At'),
            'created_by' => Yii::t('gip', 'Created By'),
            'updated_by' => Yii::t('gip', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAttributesOfType()
    {
        return $this->hasMany(\common\models\Attribute::className(), ['attribute_type_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getListOfValues()
    {
        return $this->hasOne(\common\models\ListOfValues::className(), ['id' => 'list_of_values_id']);
    }




}
