<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "dashboard_giplet".
 *
 * @property integer $id
 * @property integer $dashboard_id
 * @property integer $giplet_id
 * @property string $created_at
 * @property string $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 * @property string $aliasModel
 */
abstract class DashboardGiplet extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'dashboard_giplet';
    }

    /**
     * Alias name of table for crud viewsLists all Area models.
     * Change the alias name manual if needed later
     * @return string
     */
    public function getAliasModel($plural=false)
    {
        if($plural){
            return Yii::t('gip', 'DashboardGiplets');
        }else{
            return Yii::t('gip', 'DashboardGiplet');
        }
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['dashboard_id', 'giplet_id'], 'required'],
            [['dashboard_id', 'giplet_id', 'created_by', 'updated_by'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['giplet_id'], 'exist', 'skipOnError' => true, 'targetClass' => Giplet::className(), 'targetAttribute' => ['giplet_id' => 'id']],
            [['dashboard_id'], 'exist', 'skipOnError' => true, 'targetClass' => Dashboard::className(), 'targetAttribute' => ['dashboard_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('gip', 'ID'),
            'dashboard_id' => Yii::t('gip', 'Dashboard ID'),
            'giplet_id' => Yii::t('gip', 'Giplet ID'),
            'created_at' => Yii::t('gip', 'Created At'),
            'updated_at' => Yii::t('gip', 'Updated At'),
            'created_by' => Yii::t('gip', 'Created By'),
            'updated_by' => Yii::t('gip', 'Updated By'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(
            parent::attributeHints(),
            [
            'id' => Yii::t('gip', 'ID'),
            'dashboard_id' => Yii::t('gip', 'Dashboard Id'),
            'giplet_id' => Yii::t('gip', 'Giplet Id'),
            'created_at' => Yii::t('gip', 'Created At'),
            'updated_at' => Yii::t('gip', 'Updated At'),
            'created_by' => Yii::t('gip', 'Created By'),
            'updated_by' => Yii::t('gip', 'Updated By'),
            ]);
    }




}
