<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "device".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $device_type
 * @property string $created_at
 * @property string $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 *
 * @property \common\models\DeviceDeviceGroup[] $deviceDeviceGroups
 */
abstract class Device extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'device';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['type_id', 'created_at', 'updated_at'], 'safe'],
            [['type_id', 'created_by', 'updated_by'], 'integer'],
            [['name'], 'string', 'max' => 160],
            [['description'], 'string', 'max' => 2000],
            [['device_type'], 'string', 'max' => 40],
            [['name'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('gip', 'ID'),
            'name' => Yii::t('gip', 'Name'),
            'display_name' => Yii::t('gip', 'Display Name'),
            'description' => Yii::t('gip', 'Description'),
            'device_type' => Yii::t('gip', 'Device Type'),
            'created_at' => Yii::t('gip', 'Created At'),
            'updated_at' => Yii::t('gip', 'Updated At'),
            'created_by' => Yii::t('gip', 'Created By'),
            'updated_by' => Yii::t('gip', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDeviceDeviceGroups()
    {
        return $this->hasMany(\common\models\DeviceDeviceGroup::className(), ['device_id' => 'id']);
    }




}
