<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "device_device_group".
 *
 * @property integer $id
 * @property integer $device_group_id
 * @property integer $device_id
 * @property string $created_at
 * @property string $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 *
 * @property \common\models\DeviceGroup $deviceGroup
 * @property \common\models\Device $device
 */
abstract class DeviceDeviceGroup extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'device_device_group';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['device_group_id', 'device_id'], 'required'],
            [['device_group_id', 'device_id', 'created_by', 'updated_by'], 'integer'],
            [['created_at', 'updated_at'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('gip', 'ID'),
            'device_group_id' => Yii::t('gip', 'Device Group'),
            'device_id' => Yii::t('gip', 'Device'),
            'created_at' => Yii::t('gip', 'Created At'),
            'updated_at' => Yii::t('gip', 'Updated At'),
            'created_by' => Yii::t('gip', 'Created By'),
            'updated_by' => Yii::t('gip', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDeviceGroup()
    {
        return $this->hasOne(\common\models\DeviceGroup::className(), ['id' => 'device_group_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDevice()
    {
        return $this->hasOne(\common\models\Device::className(), ['id' => 'device_id']);
    }




}
