<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "mapping".
 *
 * @property integer $id
 * @property integer $processing_id
 * @property integer $attribute_in
 * @property integer $attribute_out
 * @property string $created_at
 * @property string $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 *
 * @property \common\models\Processing $processing
 * @property \common\models\Attribute $attributeIn
 * @property \common\models\Attribute $attributeOut
 */
abstract class Mapping extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'mapping';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['processing_id', 'attribute_in', 'attribute_out', 'created_by', 'updated_by'], 'integer'],
            [['attribute_in', 'attribute_out'], 'required'],
            [['created_at', 'updated_at'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('gip', 'ID'),
            'processing_id' => Yii::t('gip', 'Processing ID'),
            'attribute_in' => Yii::t('gip', 'Attribute In'),
            'attribute_out' => Yii::t('gip', 'Attribute Out'),
            'created_at' => Yii::t('gip', 'Created At'),
            'updated_at' => Yii::t('gip', 'Updated At'),
            'created_by' => Yii::t('gip', 'Created By'),
            'updated_by' => Yii::t('gip', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProcessing()
    {
        return $this->hasOne(\common\models\Processing::className(), ['id' => 'processing_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAttributeIn()
    {
        return $this->hasOne(\common\models\Attribute::className(), ['id' => 'attribute_in']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAttributeOut()
    {
        return $this->hasOne(\common\models\Attribute::className(), ['id' => 'attribute_out']);
    }




}
