<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "motd".
 *
 * @property integer $id
 * @property string $message
 * @property integer $new
 * @property string $created_at
 */
abstract class Motd extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'motd';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['message', 'created_at'], 'required'],
            [['message'], 'string'],
            [['new'], 'integer'],
            [['created_at'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('gip', 'ID'),
            'message' => Yii::t('gip', 'Message'),
            'new' => Yii::t('gip', 'New'),
            'created_at' => Yii::t('gip', 'Created At'),
        ];
    }




}
