<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "provider".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property integer $provider_type_id
 * @property integer $input_event_id
 * @property string $created_at
 * @property string $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 *
 * @property \common\models\Processing[] $processings
 * @property \common\models\ProviderType $providerType
 * @property \common\models\Event $inputEvent
 */
abstract class Provider extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'provider';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'provider_type_id', 'input_event_id'], 'required'],
            [['provider_type_id', 'input_event_id', 'created_by', 'updated_by'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['name'], 'string', 'max' => 40],
            [['description'], 'string', 'max' => 2000],
            [['name'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('gip', 'ID'),
            'name' => Yii::t('gip', 'Name'),
            'description' => Yii::t('gip', 'Description'),
            'provider_type_id' => Yii::t('gip', 'Provider Type ID'),
            'input_event_id' => Yii::t('gip', 'Input Event ID'),
            'created_at' => Yii::t('gip', 'Created At'),
            'updated_at' => Yii::t('gip', 'Updated At'),
            'created_by' => Yii::t('gip', 'Created By'),
            'updated_by' => Yii::t('gip', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProcessings()
    {
        return $this->hasMany(\common\models\Processing::className(), ['provider_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProviderType()
    {
        return $this->hasOne(\common\models\ProviderType::className(), ['id' => 'provider_type_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getInputEvent()
    {
        return $this->hasOne(\common\models\Event::className(), ['id' => 'input_event_id']);
    }




}
