<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "rule".
 *
 * @property integer $id
 * @property integer $device_group_id
 * @property integer $notification_group_id
 * @property integer $detection_type_id
 * @property string $name
 * @property string $description
 * @property string $created_at
 * @property string $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 *
 * @property \common\models\DeviceGroup $deviceGroup
 * @property \common\models\NotificationGroup $notificationGroup
 * @property \common\models\DetectionType $detectionType
 * @property \common\models\Subscription[] $subscriptions
 */
abstract class Rule extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'rule';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['device_group_id', 'notification_group_id', 'detection_type_id', 'name'], 'required'],
            [['device_group_id', 'notification_group_id', 'detection_type_id', 'created_by', 'updated_by'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['name'], 'string', 'max' => 40],
            [['display_name'], 'string', 'max' => 80],
            [['description'], 'string', 'max' => 2000],
            [['name'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('gip', 'ID'),
            'device_group_id' => Yii::t('gip', 'Device Group'),
            'notification_group_id' => Yii::t('gip', 'Notification Group'),
            'detection_type_id' => Yii::t('gip', 'Detection Type'),
            'name' => Yii::t('gip', 'Name'),
            'display_name' => Yii::t('gip', 'Display Name'),
            'description' => Yii::t('gip', 'Description'),
            'created_at' => Yii::t('gip', 'Created At'),
            'updated_at' => Yii::t('gip', 'Updated At'),
            'created_by' => Yii::t('gip', 'Created By'),
            'updated_by' => Yii::t('gip', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDeviceGroup()
    {
        return $this->hasOne(\common\models\DeviceGroup::className(), ['id' => 'device_group_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNotificationGroup()
    {
        return $this->hasOne(\common\models\NotificationGroup::className(), ['id' => 'notification_group_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDetectionType()
    {
        return $this->hasOne(\common\models\DetectionType::className(), ['id' => 'detection_type_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubscriptions()
    {
        return $this->hasMany(\common\models\Subscription::className(), ['rule_id' => 'id']);
    }




}
