<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "zone_zone_group".
 *
 * @property integer $id
 * @property integer $zone_group_id
 * @property integer $zone_id
 * @property string $created_at
 * @property string $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 *
 * @property \common\models\ZoneGroup $zoneGroup
 * @property \common\models\Zone $zone
 */
abstract class ZoneZoneGroup extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'zone_zone_group';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['zone_group_id', 'zone_id'], 'required'],
            [['zone_group_id', 'zone_id', 'created_by', 'updated_by'], 'integer'],
            [['created_at', 'updated_at'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('gip', 'ID'),
            'zone_group_id' => Yii::t('gip', 'Zone Group ID'),
            'zone_id' => Yii::t('gip', 'Zone ID'),
            'created_at' => Yii::t('gip', 'Created At'),
            'updated_at' => Yii::t('gip', 'Updated At'),
            'created_by' => Yii::t('gip', 'Created By'),
            'updated_by' => Yii::t('gip', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getZoneGroup()
    {
        return $this->hasOne(\common\models\ZoneGroup::className(), ['id' => 'zone_group_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getZone()
    {
        return $this->hasOne(\common\models\Zone::className(), ['id' => 'zone_id']);
    }




}
