<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace console\controllers;

use Yii;

class Movement extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'movement_eblg';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['MOVEMENT_DATE_EBLG_LT', 'FLIGHT_NUMBER', 'REGISTRATION',
				'AERODROME_ICAO_CODE', 'AERODROME_IATA_CODE', 'AERODROME_NAME',
				'SCHEDULED_TIME_OF_ARRIVAL', 'ESTIM_TIME_OF_ARRIVAL', 'ACTUAL_TIME_OF_ARRIVAL',
				'SCHEDULED_TIME_OF_DEPARTURE', 'ESTIM_TIME_OF_DEPARTURE', 'ACTUAL_TIME_OF_DEPARTURE',
				'NUMBER_OF_STAND_ON_APRON',
				'IATA_DELAY_CODE', 'IATA_DELAY_DESCRIPTION',
				'MOVEMENT_DIRECTION', 'MOVEMENT_CATEGORY',
				'AIRCRAFT_CODE_ICAO', 'WAKE_TURBULENCE_CATEGORY',
				'PARKING_PASSENGER', 'PARKING_CARGO', 'ID'], 'safe'],
        ];
    }

}
